### DEPLOY TRANSACTION CONTRACT
GET http://localhost:5000/web3/deploy/transaction
Authorization: abc

### DEPLOY TRANSACTION DETAIL CONTRACT
GET http://localhost:5000/web3/deploy/transaction-detail
Authorization: abc

### DEPLOY TOKEN CONTRACT
GET http://localhost:5000/web3/deploy/token
Authorization: abc

### DEPLOY WALLET CONTRACT
GET http://localhost:5000/web3/deploy/wallet
Authorization: abc